from goodtablesio import exceptions


class S3Exception(exceptions.GoodtablesioException):
    pass
